### ISSUE TITLE
Downloading a file using the drive API node.js example doesn't work

### ISSUE THREAD

**Issue by matlsn** [google/google-api-nodejs-client#1024]
Using the example found on [the drive REST api page](https://developers.google.com/drive/v3/web/manage-downloads) doesn't work as intended.

Node returns "cannot read property 'on' of undefined".

**Comment by thomann061** [comment]
See here:
https://github.com/google/google-api-nodejs-client/issues/963

**Comment by JustinBeckwith** [comment]
Greetings folks!  We're in the process of working out how we manage our samples.  Until that gets sorted out - I've put together a working set of samples here:
https://github.com/google/google-api-nodejs-client/pull/1028

Thanks for your patience!

**Comment by JustinBeckwith** [comment]
Greetings folks!  We've merged in the samples with a working sample in this repo.  Sadly we use a different bug system for bugs on developers.google.com.  I went ahead and filed a bug here for you:
https://issuetracker.google.com/issues/74344655

Since this one is out of our hands, I'm going to close it out.  Let me know if you have any more problems!
