### ISSUE TITLE
drive.files.create throws the error: Invalid multipart request with 0 mime parts

### ISSUE THREAD

**Issue by DSnopov** [google/google-api-nodejs-client#1083]
With `"google-auth-library": "1.3.2"` and `"googleapis": "27.0.0"` installed uploading to drive throws the `Invalid multipart request with 0 mime parts` error. Here is the code:
```javascript
const {OAuth2Client} = require('google-auth-library')
const {google} = require('googleapis')

const googleOAuth2Client = new OAuth2Client({clientId: GOOGLE_DRIVE_CLIENT_ID})
googleOAuth2Client.setCredentials(tokens)
const googleDrive = google.drive({
  version: 'v3',
  auth: googleOAuth2Client
})

googleDrive.files.create({
  resource: {
    name: 'test.png',
    parents: [parentId]
  },
  media: {
    mimeType: 'image/png',
    body: fs.createReadStream('/Users/dmitry/Desktop/test.png')
  }
}, function (err, response) {
  if (err) {
    console.error(err)
    reject(err)
    return
  }
  console.log(response.data)
})
```
As mentioned [here](https://stackoverflow.com/questions/48492592/google-drive-sdk-with-node-js-googleapis-package-throws-error-invalid-multipart) and [here](https://stackoverflow.com/questions/48526185/google-drive-upload-api-invalid-multipart-request-with-0-mime-parts?noredirect=1&lq=1), it works with `"googleapis": "24.0.0"`, so it looks like the request -> axios change is the reason for this issue. Or am I missing something? There is no much information in [the code sample on github](https://github.com/JustinBeckwith/google-api-nodejs-client/blob/master/samples/drive/upload.js) (yeah, I realize that all the code samples from docs are currently not working).

**Comment by JustinBeckwith** [comment]
Well this is weird.  I updated the sample locally here and added the name and mimeType fields, and this totally "just works" for me:
https://github.com/JustinBeckwith/google-api-nodejs-client/blob/master/samples/drive/upload.js

A few things that could be going wrong here:

1. **Please remove `google-auth-library` from your package.json. **.  Then run `npm install` again to clean things up.  This library comes with a version of it pre-installed, and it's very important you use that version.  As per the readme, you can get an OAuth2Client this way:

```js
const {google} = require('googleapis');
const OAuth2 = google.auth.OAuth2;
const oauth2Client = new OAuth2(
  YOUR_CLIENT_ID,
  YOUR_CLIENT_SECRET,
  YOUR_REDIRECT_URL
);
```

2. **Check the scopes on your tokens**.  I don't know how you're setting the scopes, or how you're acquiring your tokens.  Can you show a complete sample that includes this part? 

3. Are you setting any global options?  

Anything you can share that would help me reproduce this would be *super* helpful.  Thanks!

**Comment by DSnopov** [comment]
Thanks for the reply @JustinBeckwith!

1. It didn't work with the pre-installed auth library
2. The scope was `https://www.googleapis.com/auth/drive`
3. No

You are right. The important thing I didn't mention was that this issue happens in the Electron environment. After your reply, I tried to reproduce it in Node, but everything worked as expected. So, after some research, I found out that axios uses the XHR adapter in Electron because both XHR and Node are available. I had to manually set the HTTP adapter, as specified [here](https://github.com/axios/axios/issues/552), and everything worked!

Here is the complete example of the drive initialization in Electron for anyone interested:
```javascript
const {google} = require('googleapis')
google.options({adapter: require('axios/lib/adapters/http')})

const oAuth2Client = new google.auth.OAuth2({
  clientId: GOOGLE_DRIVE_CLIENT_ID
})
oAuth2Client.setCredentials(tokens) // tokens you acquired during the authentication step

const googleDrive = google.drive({
  version: 'v3',
  auth: oAuth2Client
})
```
Do you guys officially support Electron for this lib? Just wondering whether this should be specified in the readme.

Thanks!

**Comment by gorangio** [comment]
I don't mean to hijack this thread, but it seemed appropriate.
I have a similar problem where the "resource" parameter causes the same reported issue.  (Note also the query parameter does nothing as reported in issue #1076). Seeing this question & solution, I did the same mods (removed google-auth-library from the package.json, run 'npm install', and ensured googleapis v27 was in place). However I'm now running into a series of other issues. 

First, running the exact same code which includes a "var gAuth = require('google-auth-library');" results in:
```
module.js:327
    throw err;
    ^
Error: Cannot find module 'google-auth-library'
...
```
Rather than changing the whole auth scheme in that code, I choose to try the examples and build from there. The best start seemed to be the example code in "Generating an authentication URL" from the guide JustinB recommended, https://github.com/google/google-api-nodejs-client/#generating-an-authentication-url.  However that resulted in two basic errors.
First:
```
gAPIs/au.js:11
var {google} = require('googleapis');
    ^
SyntaxError: Unexpected token {
```
Why does this fail?
Fixing that by removing the surrounding brackets, resulted in the second:
```
gAPIs/au.js:12
var OAuth2 = google.auth.OAuth2;
                        ^
TypeError: Cannot read property 'OAuth2' of undefined

```
Looks like the "auth" function is not in the googleapis.  
I'll keep making other attempts, but I thought someone could resolve this basic use of example code from the guides.

**Comment by DSnopov** [comment]
This issue was reintroduced after replacing axios with gaxios in [v37.0.0 ](https://github.com/googleapis/google-api-nodejs-client/releases/tag/v37.0.0). Again, it only happens in Electron **renderer** process.

**Comment by m4heshd** [comment]
@DSnopov This is my 2nd day being wasted on trying to find a solution for this other than IPC. Any workaround?
