### ISSUE TITLE
Permissions issue with service account client

### ISSUE THREAD

**Issue by pauldariye** [google/google-api-nodejs-client#1119]
I'm sure I missed this in the documentation but I seem to not be able to access the files created using the service account client.

Any suggestions on how to fix this?

**Comment by JustinBeckwith** [comment]
Greetings!  Can you provide a few more details?
- What API are you trying to use?  Is this for drive?
- Can you share a code snippet?  Is the issue with create? list? get?

Thanks!

**Comment by pauldariye** [comment]
I'm using the `drive` API. Also, I'm using the `create` method, pretty much same as the example in the[ documentation for node](https://developers.google.com/drive/v3/reference/files/create)

**Comment by JustinBeckwith** [comment]
Thanks!  Could you share the actual code though?  It would be nice to see which parameters you're trying to use so I can re-create the problem.

**Comment by pauldariye** [comment]
Hey @JustinBeckwith, the code is [here](https://github.com/pauldariye/issue-er/blob/master/src/lib/google.js). 

Also, I'm still having issues with the jwt token authentication.

**Comment by JustinBeckwith** [comment]
Hey @pauldariye - is this still a problem?  One thought I had - if this is working locally but not in the cloud, it either means a.) you have an env var mixup problem, or b.) there may be a mismatch of your local npm modules vs what's installed in your cloud environment. 

I would try doing a `rm -rf node_modules`, `npm install`, and see if it still works locally.  

In the meantime - it's been a week since I heard anything here, and as far as I can tell we don't have a bug.  If you can provide a repo here, I'd be happy to open the issue again :)

**Comment by pauldariye** [comment]
Closing this as it's now a nonissue @JustinBeckwith
