### ISSUE TITLE
"details" field missing in error responses

### ISSUE THREAD

**Issue by acchou** [google/google-api-nodejs-client#1152]
The REST api responds with useful details if the request is invalid. For example, using the API explorer for https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions/generateUploadUrl:

```javascript
{
  "error": {
    "code": 400,
    "message": "The request has errors",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "region",
            "description": "region us-west1 is not supported."
          }
        ]
      }
    ]
  }
}
```

The equivalent request using the node client gives a less helpful response:
```javascript
{
  "error": {
    "code": 400,
    "message": "The request has errors",
    "errors": [
      {
        "message": "The request has errors",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

A full example is in this repo: https://github.com/acchou/gcloud-example/tree/errordetails
```shell
$ yarn install
$ node --harmony build/index.js
```

**Comment by acchou** [comment]
The example is a bit elaborate for the purposes of showing this issue, I can reduce it if it helps. The main source file to examine is src/cloudfunctions.ts.

**Comment by acchou** [comment]
This issue is really making it difficult to use the Cloud Functions API; the error messages returned by API requests are very opaque, and I have to manually go to the API Explorer web page and enter each message field manually to get a detailed error response.

**Comment by JustinBeckwith** [comment]
This is super weird.  I can verify that these details come back in postman, but they're not showing up when we make the request through google-auth-library and axios.  I need to dig deeper to find out where the details are getting stripped and why.

**Comment by JustinBeckwith** [comment]
Well this is an adventure!  It turns out that the googleapis endpoint we're calling returns different results based on the user-agent included in the request 😦 

If I include the `User-Agent` header of`google-api-nodejs-client/30.0.0 (gzip)`, I get no `details` field.  If I leave it out, I get the details.

**Comment by JustinBeckwith** [comment]
Ok!  Mystery solved. When the `google-api-nodejs-client` user agent is set, the details are sent as part of a `debugInfo` property which hangs off of the individual `error` objects. 

For me, but the information you're looking for is in:

`e.response.data.error.errors[0].debugInfo`.

However... the punchline is that this data is only available when requests are made from **inside of a google network**.  You're getting this data back with the API explorer because it runs at Google.  If you make a request from outside of our network... the details won't be included sadly.

Sadly, there isn't anything I can do about this from the client library.  This is a change that would have to be made on the API back end.  I will poke around and see who I can ask, but I wouldn't expect anything soon :(

**Comment by acchou** [comment]
Well thanks for taking a look at it. Needless to say, it's difficult to debug requests when there are no details on why requests are rejected... and it's sad that someone put in a lot of effort into writing detailed error messages into the responses but they're not making it back to anyone outside of Google :(

**Comment by JustinBeckwith** [comment]
I hear you.  I've opened up an internal bug, and I'm tracking down a few folks to chat next week.  I mostly just closed this issue because it's not actionable for us on the client side (in this code base).  I'll keep diggin!
