### ISSUE TITLE
Internal error while excel updating

### ISSUE THREAD

**Issue by kutlaykural** [google/google-api-nodejs-client#1227]
Hello everyone,
While updating an excel sheet it gives an error like this:
```
{ Error: Internal error encountered.
    at createError (/Users/us/Desktop/google2/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/us/Desktop/google2/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/Users/us/Desktop/google2/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:110:20)
    at Unzip.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
My code is below:
```js
var service = google.sheets('v4');
var body = {
    range: "EmployeeInfo!A5:B",
    values: [ ["A value","B value"]]
};
service.spreadsheets.values.update({
    auth: auth,
    spreadsheetId: "1iny9VgD-8rXdaq3tSqRoZQwM58a-byEb",
    range: "EmployeeInfo!A5:B",
    valueInputOption: "USER_ENTERED",
    resource: body
}, function(err, result) {
    if(err) {
      // Handle error
      console.log(err);
   } else {
      console.log('%d cells updated.', result.updatedCells);
    }
});
```

Is there anybody have any idea?
Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Sometimes its helpful to start with the API explorer to figure out some of these parameters. Have you tried playing with this?
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update

So I haven't tried this code, but it's worth breaking the `auth` parameter out, and using `requestBody` instead of `resource`.  Can you give this a try?

var service = google.sheets({
  version: 'v4',  auth
});

const res = await service.spreadsheets.values.update({
    spreadsheetId: "1iny9VgD-8rXdaq3tSqRoZQwM58a-byEb",
    range: "EmployeeInfo!A5:B",
    valueInputOption: "USER_ENTERED",
    requestBody: {
      range: "EmployeeInfo!A5:B",
      values: [ ["A value","B value"]]
  }
});
console.log(res.data);
```

The sheets `update` command can be really tricky.  Hope this helps!

**Comment by cvonk** [comment]
The API has a default quota of 100 reads/day. After that it throws a meaningless error message such as Internal Error Encountered. I suddenly encountered these errors, even though I didn't change any of my code [github].
