### ISSUE TITLE
Using query example, and sampleclient - can't get to the point of server creation

### ISSUE THREAD

**Issue by fillipvt** [google/google-api-nodejs-client#1272]
Hello,

Just downloaded the [query example here](https://github.com/google/google-api-nodejs-client/blob/master/samples/webmasters/query.js), installed the necessary packages (open, server-destroy, fs, googleapis, path) and while using [sampleclient](https://github.com/google/google-api-nodejs-client/blob/master/samples/sampleclient.js) found that the code runs only up to the `this.oAuth2Client.generateAuthUrl` call. In that sense the server doesn't start and I seem to be stuck at this page:

![image](https://user-images.githubusercontent.com/16828078/43664210-bcf95848-9731-11e8-88ec-2a88b7c2816e.png)
What do I do with this code? There's no prompt in the console.

The only changes I've made are using `oauth.keys.json` with the API info, following this format (a direct download from the API Console):
```
{
  "installed": {
    "client_id": "CLIENT_ID,
    "project_id": "PROJECT_ID,
    "auth_uri": "AUTH_UTI",
    "token_uri": "TOKEN_URI,
    "auth_provider_x509_cert_url": "CERT_URL",
    "client_secret": "CLIENT_SECRET",
    "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
  }
}
```
And setting `siteUrl` to one of our websites inside the query example.

Those two are the only changes. I would appreciate any guidance given.

Thanks

**Comment by JustinBeckwith** [comment]
Ok - so this was a fun adventure!  I have an end to end sample working right here:
https://github.com/JustinBeckwith/googleapis-1272

The issue here is the use of an "Installed application" OAuth2 key file vs the "Web Application" key file.  The installed app keyfile makes a few assumptions:

1. The redirectUrl is just http://localhost
2. The redirectUrl is in fact the 2nd element in the array, not the first. 
3. The key data is in `installed` instead of `web`:

The relevant change in `sampleClient.js` is:

```js
if (fs.existsSync(keyPath)) {
  const keyFile = require(keyPath);
  keys = keyFile.installed || keyFile.installed;
}
```

Pay special attention to the `keys.redirect_uris[1]` here:

```js
// create an oAuth client to authorize the API call
    this.oAuth2Client = new google.auth.OAuth2(
      keys.client_id,
      keys.client_secret,
      keys.redirect_uris[1]
    );
```

Your keyfile should have the appropriate redirectUrl:

```js
{
  "installed": {
    "client_id": "*******.apps.googleusercontent.com",
    "project_id": "YOUR PROJECT ID",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://www.googleapis.com/oauth2/v3/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "*****",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost:3000/oauth2callback"
    ]
  }
}
```

Pay special attention to the `redirect_uris` here :)  The combination of my source, and this should get you up and running.  Please do let me know if you run into other issues!  I'm going to keep this open as a way to track improving the error messages and documentation in the samples so that others don't fall into this pit.

Good luck!

**Comment by fillipvt** [comment]
Justin! Than you very much! It worked perfectly! 

Sorry to have taken so long to answer the only notification I received was when the issue got closed.

Thanks again. That example repo came in just hte perfect moment.
