### ISSUE TITLE
Possible to load client_secret JSON ?

### ISSUE THREAD

**Issue by timcash** [google/google-api-nodejs-client#266]
1.) Instead of setting the clientid secret and redirect manually is it possible to load the JSON file one can download from the Developer Console? 

2.) Is there a list somewhere of what scopes are need for each service? I am having trouble getting the compute api to work. Could the apis load the scopes needed implicitly?

3.) Just to make sure, I need to use the Oauth2 "installed application" option for this api correct?

**Comment by rainabba** [comment]
This is days in the works, but will hopefully help clear a thing or two up. "google-api-nodejs-client examples using JWT and service account" https://gist.github.com/rainabba/25d1972f455b71916952

**Comment by sarlv** [comment]
I have same problem. 
http://stackoverflow.com/questions/36528336/google-drive-cant-get-push-notifications

**Comment by JustinBeckwith** [comment]
Greetings!  The docs here have improved a great deal over the last *looks down* 4 years.  If this is still an issue - feel free to open a new bug!

**Comment by rainabba** [comment]
Updated after my 3rd attempt in 2 years to get Drive support in my node app, but being thwarted by volumes of confusing documents, conflicting examples and various approaches. As of 2018-05-09, this approach is "current" in that is uses the latest approach from the console, but it uses API v25 because v29 breaks completely with these samples and I can't find any docs that address those issues.

Here's my updated gist that requires a client_secret.json, will provide a URL, take the code and save a .token file next to the source .json. It uses the Nodejs debugger to halt code and get the code value in the debugger because I was having issues that made me leary about the console and the debugger works so well anyway :)

https://gist.github.com/rainabba/25d1972f455b71916952

**Comment by JustinBeckwith** [comment]
@rainabba sorry to hear you've had so much trouble.  Can you share an example of a broken sample with v29?  I'd love to fix it.  Everything in [here](https://github.com/google/google-api-nodejs-client/tree/master/samples/drive) should be working :)

**Comment by rainabba** [comment]
This explains that particular challenge: https://github.com/google/google-api-nodejs-client/pull/1158

I was so caught up in the keys for a while that I'd missed the obvious. That code is what got me as far as the above gist btw. With it I learned the flow and rebuilt it.

Now that I FINALLY have a token, it's time to see if I can do what I've set out to, saving PDFs directly to Drive.

**Comment by rainabba** [comment]
Just over a month later and I've finally released node-cloudfs-drive: https://www.npmjs.com/package/node-cloudfs-drive

Hopefully this will fill the gap I see at least 10 other projects trying to do (or had tried in the past) and I intend to maintain this for at least a couple years unless Google finally pushes me over the edge with more anti-enterprise behavior on Drive (like not letting me install Drive File Stream on a server, or throttling my API calls so that I can't have a properly optimized lookup system with our 100,000's of objects we maintain there). That's another convo though :)
