### ISSUE TITLE
Prediction API => "Model name is empty."

### ISSUE THREAD

**Issue by davidemiceli** [google/google-api-nodejs-client#333]
Sorry a question, I have:

	var google = require('googleapis');
	var prediction = google.prediction('v1.6');

	var train =
	'...';

	var authClient = new google.auth.JWT(
	    '5578575756-balblabla@developer.gserviceaccount.com',
	  // use the PEM file we generated from the downloaded key
		"g_privatekey.pem",
	    // Contents of private_key.pem if you want to load the pem file yourself
	    // (do not use the path parameter above if using this param)
	    // Scopes can be specified either as an array or as a single, space-delimited string
	    null,
	    ['https://www.googleapis.com/auth/prediction']
	    // User to impersonate (leave empty if no impersonation needed)
	    );

	authClient.authorize(function(err, tokens) {
	  if (err) {
	    console.log(err);
	    return;
	  } else {
		console.log(tokens);
		prediction.trainedmodels.insert({
			auth: authClient,
			project: 'projectAppTest',
			id: '152fdh621r2ref1262',
			resource: train}, function(err, result) {
		  console.log('Result: ' + (err ? err.message : result));
		});
	  }
	});

But I have as result log message: "Model name is empty", why? It's missing some parameters?

Thanks for a response...

**Comment by JustinBeckwith** [comment]
Greetings!  Apologies for taking so long to get back to you.  Since this was filed, we released a proper API for using the prediction API:

https://github.com/GoogleCloudPlatform/gcloud-node#google-prediction-api

Could you give that a try instead?  If this is still an issue, please feel free to re-open.

Thanks!

**Comment by jmdobry** [comment]
It may have been that your model hadn't finished training yet. If the model is done training, then `analyze` should return more information about the model, like its confusion matrix. Instead of `analyze` you could simply call `get` with the model id to get its status. When it's done, the response will look something like this:

```js
{
 "kind": "prediction#training",
 "id": "118asd2e24-1299-4440-a335-0asdf4d1asdf54",
 "selfLink": "https://www.googleapis.com/prediction/v1.6/projects/label-cat/trainedmodels/118asd2e24-1299-4440-a335-0asdf4d1asdf54",
 "created": "2015-11-12T19:53:30.253Z",
 "trainingComplete": "2015-11-12T19:56:41.297Z",
 "modelInfo": {
  "numberInstances": "2359",
  "modelType": "classification",
  "numberLabels": "2",
  "classificationAccuracy": "0.91"
 },
 "trainingStatus": "DONE"
}
```

At which point you should be able to use `predict`.
