### ISSUE TITLE
appsactivity.activities.list with jwt auth always returns 400

### ISSUE THREAD

**Issue by skhavari** [google/google-api-nodejs-client#356]
#### Repro
Run the sample code below

#### Expect
It to output the users activity list for their top level google drive folder

#### Actual
Always returns 400

```javascript
var google = require('googleapis');
var appsActivities = google.appsactivity('v1');
var util = require('util');

var jwtClient = new google.auth.JWT(
  '<email>',
  './key.pem',
  null,
  [ "https://www.googleapis.com/auth/activity",
    "https://www.googleapis.com/auth/admin.reports.audit.readonly",
    "https://www.googleapis.com/auth/admin.reports.usage.readonly", 
    "https://www.googleapis.com/auth/drive"],
  '<user-email-addr>');

jwtClient.authorize(function(err, tokens) {
  if (err) {
    log(err);
    return;
  }

  appsActivities.activities.list( {auth: jwtClient, userId: "me"}, function(err, resp){
    log(err);
    log(resp);
  });
});

function log(object){
  console.log(util.inspect(object, {showHidden: false, depth: null}));
}
```

**Comment by ryanseys** [comment]
You cannot use a JWT to authorize these Google Apps Activity requests, you must use OAuth 2.0. See [here](https://developers.google.com/google-apps/activity/v1/guides/auth) for more information. 

This is because JWT essentially authenticates to Google as a new user, not as an existing user. Because of this, there's no way the JWT has access to any user data or user-facing features such as Google Apps, including all the data for yourself. Another good example of this is in #347.

Please use OAuth 2.0 and let me know how that works out.

**Comment by skhavari** [comment]
rock n roll!
