### ISSUE TITLE
JWT auth for blogger gives error 403

### ISSUE THREAD

**Issue by khanh-nguyen** [google/google-api-nodejs-client#379]
I try to use JWT with Blogger API
```
var jwtClient = new google.auth.JWT(serviceAccount,
        /path/to/key
        null,
        ['https://www.googleapis.com/auth/blogger']
    ),
    blogger = google.blogger({version: 'v3', auth: jwtClient});
    
jwtClient.authorize(function(err, tokens) {
    blogger.posts.insert({
        blogId: 'id-number',
        title: 'title here',
        content: 'Just a simple test'
    }, function(err, resp) {
        if (err) throw err;
        console.log('Post inserted!');
    });
});    
```
but get error `{ [Error: We're sorry, but you don't have permission to access this resource.] code: 403 }`.
`blogger.posts.get` works just fine. The given scope allows to view and manage posts. So, I'm not clear what is wrong.

**Comment by h2non** [comment]
I'm have a similar issue when uploading a video to Youtube. If I use the FWT authentication mode, I'm getting a 401, however I can perform read operations correctly using FWT. 
It's seems like some write operations are not support by this type of authentication and requires end user validation using OAuth. For server-to-server automation this is very painful. 

Could someone confirm this?

**Comment by ryanseys** [comment]
You cannot use JWT for these types of requests. Any requests that is public can be authenticated in any way (e.g. API Key, OAuth2, JWT) however if you need to manage anything private (such as create a post, delete a post) you must be authenticated with OAuth2.

See here: https://developers.google.com/blogger/docs/3.0/using#auth

It also makes sense that you need to authenticate with a real Google account using OAuth2 rather than JWT to upload a youtube video because the youtube video is associated with a specific Google account.

Each API has their own section on authorization that is independent of the other APIs. You'll need to read the docs for each API in order to asses what your application needs in order to authenticate properly.

**Comment by h2non** [comment]
Thanks for the answer. 

Therefore how it's possible to automate server-to-server tasks using OAuth when a web browser cannot we available? I've some possible, but all are ugly workarounds, such as using PhantomJS

**Comment by ryanseys** [comment]
I would suggest authenticating with OAuth2 using a browser and then storing the credentials (access token and refresh token) in a safe place and using them in your application. If your access token expires, use your refresh token to get a new one. Uploading a YouTube video shouldn't be a strictly server-to-server thing, because an end user needs to authenticate their account anyway. Even if that's your own YouTube account. 

See here for the different flows you could use to accomplish that: https://developers.google.com/youtube/v3/guides/authentication#OAuth2_Flows

**Comment by khanh-nguyen** [comment]
:+1: Thanks @ryanseys.
I had to spin up selenium server to did browser oauth. Will try to use refresh token.

**Comment by h2non** [comment]
Thanks for the tips. 

I've created this packages to provide automation and remove headaches when dealing with OAuth2:
https://github.com/h2non/nightmare-google-oauth2
https://github.com/h2non/google-oauth2-token (CLI only)

**Comment by khanh-nguyen** [comment]
@ryanseys I followed this [sample code](https://github.com/google/google-api-nodejs-client/blob/master/examples/oauth2.js) to get access token, setting `access_type = 'offline'` and `scope = 'https://www.googleapis.com/auth/blogger'`, but I couldn't get the refresh token. Here's what I got back:
```
{ 
  access_token: 'ya29.xxx',
  token_type: 'Bearer',
  expiry_date: 1425451432976 
}
```
Do you know why so?
