### ISSUE TITLE
manually refreshing a token

### ISSUE THREAD

**Issue by bloodhawk** [google/google-api-nodejs-client#427]
I'm having trouble refreshing tokens. I keep getting { [Error: internal_failure] code: 500 } for the error. The refreshToken I'm supplying is valid. I am setting the credentials before calling this method:

```
oAuth2Client.refreshAccessToken(function(err, tokens) {
   console.log(err, tokens);
});
```

**Comment by bloodhawk** [comment]
I'm doing the request with curl and it is working.

**Comment by unerh** [comment]
Does anyone have any updates on this by any chance? I've experienced a similar problem. Manual refresh using the function above was working and suddenly stopped sending a refresh token.

**Comment by knownasilya** [comment]
How do you refresh the token if you don't set an access type and the token expires after one day.

See my question on SO http://stackoverflow.com/questions/39750289/getting-refresh-token-using-googleapis-lib

**Comment by JustinBeckwith** [comment]
Greetings folks!  There's a great example of refreshing the access token here:
https://github.com/google/google-auth-library-nodejs/blob/master/examples/refreshAccessToken.js

If you still have trouble, let us know!

**Comment by pitops** [comment]
@JustinBeckwith link is no  longer valid

**Comment by janvda** [comment]
@JustinBeckwith indeed link is no longer valid

**Comment by bcoe** [comment]
@janvda here's some docs on [how the OAuth 2.0 client library works](https://github.com/googleapis/google-auth-library-nodejs#oauth2).

The first time you authenticate, you should store the `refresh_token`, subsequently when you create an auth instance, you should do something like this:

```
const auth = new GoogleAuth({
  credentials: {
    "client_id": "foo.apps.googleusercontent.com",
    "client_secret": "[redacted]",
    "refresh_token": "[redacted]",
    "type": "authorized_user"
  }
}
const authClient = await auth.getClient();
const project = await auth.getProjectId();
const res = await compute.zones.list({ project, auth: authClient });
```

As long as you've stored the refresh token when authenticating, and then provide it when instantiating subsequent clients, refreshing should happen automatically on the first request (or when the token is getting close to expiring).

If you run into issues with it refreshing let us know.

**Comment by janvda** [comment]
@bcoe thanks for the response

My issue: 

I would like to use the google photos API.
For this I am using 
1/ https://github.com/roopakv/google-photos +
2/ for the google authentication I am using this library (= https://github.com/googleapis/google-api-nodejs-client).

I don't know how I can use 2/ to refresh the access token so that I can pass that to 1/.
The problem with 2/ is that it is automatically refreshing the access token when using the google APIs provided by 2/ but I am not using any of the google APIs provided by 2/.

Note also that 2/ doesn't provide the google photos API which is the only API I want to use !
