### ISSUE TITLE
your list api is calling wrong url which it is a changes url

### ISSUE THREAD

**Issue by skyhtk** [google/google-api-nodejs-client#438]
```js
list: function(params, callback) {
  var parameters = {
    options: {
      url: 'https://www.googleapis.com/drive/v2/changes',
      method: 'GET'
    },
    params: params,
    requiredParams: [],
    pathParams: [],
    context: self
  };

  return createAPIRequest(parameters, callback);
},
```

**Comment by jmdobry** [comment]
The code you're posted refers to [`drive.changes.list`](https://github.com/google/google-api-nodejs-client/blob/master/apis/drive/v2.js#L182), which in turn hits [`https://www.googleapis.com/drive/v2/changes`](https://developers.google.com/drive/v2/reference/changes/list). Everything is correct. See https://developers.google.com/drive/v2/reference/changes/list

If you're wanting to list a different resource, then you need to access that resource, e.g. `drive.comments.list`, `drive.children.list`, etc.

**Comment by jmdobry** [comment]
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client
