### ISSUE TITLE
Wrong client id / secret still results in a valid response

### ISSUE THREAD

**Issue by mderazon** [google/google-api-nodejs-client#449]
I am trying to obtain user information from an access token that I got from my mobile app that was sent to the server. Up until now I was doing an unauthenticated call to the api:
```
GET https://www.googleapis.com/plus/v1/people/me?access_token=TOKEN
```
All was fine until I started getting `dailyLimitExceededUnreg` errors.

So I want to start making authenticated requests. I have generated a client id + secret pair from the api console and tried doing the following :
``` js
var google = require('googleapis');
var plus = google.plus('v1');
var OAuth2 = google.auth.OAuth2;
var oauth2Client = new OAuth2(CLIENT_ID, CLIENT_SECRET);

oauth2Client.setCredentials({
  access_token: USER_ACCESS_TOKEN // obtained from the mobile app
});

plus.people.get({ userId: 'me', auth: oauth2Client }, function(err, response) {
  // ...
});
```

It seems that no matter what I put in the `CLIENT_ID` or `CLIENT_SECRET` or even if I don't put anything, the request still goes through and I get the user's details. It leads me to the understanding that my request is still unauthenticated.

First, I think that if I supply a client id / secret the package should at least warn you if they are wrong and that you are trying to make an authenticated request but the request is in fact not authenticated.

Second, should I assume that if I supplied the correct id / secret then everything should be fine ? Or am I missing something ?

**Comment by MySidesTheyAreGone** [comment]
You're missing something :)

If you haven't figured it out yet, if you have a user interface you need to implement the entire circus - send the user to the auth page on google.com, get the token back etc. etc. The procedure is explained here.

Otherwise if you have a headless script you need a REFRESH token using a differe auth process called "Google auth for devices" (or something like that). That kind of token can simply be reused over and over to generate new access tokens, so usually you just save it somewhere and keep it forever.

Here's an implementation - I have to warn you, though, that those tokens don't give you access to ALL of the scopes. You'll find a list of scopes you can use if you follow the second link.

https://github.com/oliverwoodings/google-device-auth

https://developers.google.com/identity/protocols/OAuth2ForDevices?hl=en#allowedscopes

**Comment by jmdobry** [comment]
We're working on improving the documentation for for authenticating and authorization, but yeah, @MySidesTheyAreGone is right. 

From the [Google+ API authorization docs](https://developers.google.com/+/web/api/rest/oauth):

> You can use the API key you get when defining your project, or you can use an OAuth 2.0 access token.

Some samples:
* Use an API key to hit google+ API: https://github.com/google/google-api-nodejs-client/blob/master/samples/multiple.js
* Headless OAuth2 flow as was mentioned: https://github.com/google/google-api-nodejs-client/blob/master/samples/oauth2.js

**Comment by jmdobry** [comment]
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client
