### ISSUE TITLE
Ad Exchange Buyer API v1.3 insert creative does not work!

### ISSUE THREAD

**Issue by dgaubert** [google/google-api-nodejs-client#459]
I've got an issue when I try to insert a new creative using Ad Exchange Buyer API v1.3. I can authenticate, list and get any creative, but insert a new creative doesn't work.

Inserting any creative always I receive the following error: **400, accountId missing from resource path.**. 

Doing some investigations the API send the POST data using query parameters instead the request body. I see that the documentation talks about [request-body](https://developers.google.com/ad-exchange/buyer-rest/v1.3/creatives/insert#request-body). Furthermore, I can't configure the client in order to change the behavior.

Regards.

**Comment by dgaubert** [comment]
I was right. I forked the repository and I fixed the issue and finally I can send creatives to the server. I don't know if this fix works for every API. I don't know if POST method is implemented on the same way for every API.

Does anybody have checked this client before?. I think that never worked.

Meanwhile, I'm going to use our forked repo, I hope your fix soon.

**Comment by jmdobry** [comment]
Can you show code that I can use to reproduce the issue you were seeing?

To send resource data like `accountId`, you put it in a `resource` object as part of what you pass to the request:

```js
adexchangebuyer.creatives.insert({
  resource: {
    accountId: 1234,
    advertiserName: '<advertiser-name>',
    buyerCreativeId: '<buyer-creative-id>',
    clickThroughUrl: [
      '<some-click-through-url>'
    ],
    height: 100,
    width: 100
  }
}, function (err, response) {
  // ...
});
```

**Comment by jmdobry** [comment]
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client
