### ISSUE TITLE
'Not Found' for searchanalytics.query, must encode siteUrl

### ISSUE THREAD

**Issue by mz3** [google/google-api-nodejs-client#476]
Once auth'd up, I run

``` javascript
 var params = {
   auth: oauth2Client,
   siteUrl: 'http://my-domain.com/',
   resource: {
      startDate: '2015-09-01',
      endDate: '2015-09-30',
      dimensions: ['page']
   }
 };

  webmasters.searchanalytics.query(params, function(err, res) {
    if(err) console.log("err:", err);
    if(res) console.log("res:", res);
  });
```

Output gives:

```
res: 'Not Found'
```

All other API calls work, such as listing sites or sitemaps, and I definitely have access to the siteUrl specified. What is going wrong here?

**Comment by nekuz0r** [comment]
You should `encodeURIComponent(siteUrl)` first.

Otherwise `https://www.googleapis.com/webmasters/v3/sites/{siteUrl}/searchAnalytics/query`
(see https://github.com/google/google-api-nodejs-client/blob/master/apis/webmasters/v3.js#L57)
will be resolved to
`https://www.googleapis.com/webmasters/v3/sites/http://my-domain.com/searchAnalytics/query`
instead of
`https://www.googleapis.com/webmasters/v3/sites/http%3A%2F%2Fmy-domain.com/searchAnalytics/query`

**Comment by bllevy** [comment]
I'm getting this same error. 

I have delegated ownership of a site and can successfully pull private site data via the API Explorer, but when I attempt to query the search console via nodejs and the webmasters v3 library, I receive a "Not Found" response. 

Any advice?
