### ISSUE TITLE
Ability to convert inserted file to Google docs

### ISSUE THREAD

**Issue by Dharmoslap** [google/google-api-nodejs-client#483]
Would be great to have there ability to upload file directly as Google docs file, like here https://developers.google.com/drive/web/manage-uploads#importing_to_google_docs_types_wzxhzdk7wzxhzdk8. Just with a convert parameter.

**Comment by jmdobry** [comment]
I'm not sure what "just with a convert parameter" means, but you can upload a file as a Google docs file. In fact the docs you linked to show a Node.js sample that uses google-api-nodejs-client to do just that.

**Comment by jmdobry** [comment]
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client
