### ISSUE TITLE
Using autocomplete in JSON API

### ISSUE THREAD

**Issue by bobvanluijt** [google/google-api-nodejs-client#494]
I can't find the answer to these basic questions: Can I use autocomplete in the JSON API? If so, does a request for autocomplete count as a 'hit'.

AC is described here: https://developers.google.com/custom-search/docs/tutorial/autocomplete
Question also asked here: http://stackoverflow.com/questions/33897927/google-cse-autocomplete-json-api

PS:
I know this isn't really an 'issue', but I'm looking for the answer for quite some time now and I can't find it.

**Comment by jmdobry** [comment]
I don't see any autocomplete in the [JSON API](https://www.googleapis.com/discovery/v1/apis/customsearch/v1/rest) itself, and I think autocomplete is a feature of the client-side JavaScript widget. If you're doing autocomplete from the server with google-api-nodejs-client, then I assume you're manually sending the partial searches yourself, in which case, yes, each search query counts towards your quota and billing.

Questions about the JSON API itself are probably more appropriately asked the the [Custom Search support channels](https://developers.google.com/custom-search/docs/support).

**Comment by jmdobry** [comment]
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client
