### ISSUE TITLE
Changing the owner of a file

### ISSUE THREAD

**Issue by dottodot** [google/google-api-nodejs-client#496]
I've tried using 

```
drive.permissions.insert({
          'fileId': fileid,
          'resource': body
})
```

and I get an  error `Error: Bad Request. User message: "You can't yet change the owner of this item. (We're working on it.)`

I assume I'm not doing anything wrong and this is a feature that coming soon. Please can you clarify this and when it will be available.

**Comment by jmdobry** [comment]
The v2 and v3 Drive APIs have a [`drive.permissions.update` endpoint](https://developers.google.com/drive/v3/reference/permissions/update) which may do what you wish (as opposed to `insert`). `update` has a `transferOwnership` option. Here is the relevant source code in google-api-nodejs-client: https://github.com/google/google-api-nodejs-client/blob/master/apis/drive/v3.js#L802

google-api-nodejs-client is just a generated wrapper around the REST APIs, and should support whatever they support. I can't speak to the future feature roadmaps of the various Google APIs. For that you may have to go through a different channel, such as [Google Drive REST API support](https://developers.google.com/drive/v3/web/support).

**Comment by jmdobry** [comment]
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client
