### ISSUE TITLE
How to send a gmail using this node app ? THIS IS NOT AN ISSUE

### ISSUE THREAD

**Issue by vivinRajagopalan** [google/google-api-nodejs-client#514]
Hi Team,

Could you please let me know how to send a GMAIL using this API? IT would be of great help.

Thanks

**Comment by barca** [comment]
you would use the `gmail.users.messages.send` function

**Comment by vivinRajagopalan** [comment]
Hi Tyler,

Thank you so much for the response. Do you have any sample code on how you
are able to send the GMail using the above API.

Thanks in advance !

Regards,
Vivin

**Comment by jmdobry** [comment]
Hi Vivin,

Here is a [Node.js quickstart](https://developers.google.com/gmail/api/quickstart/nodejs) for the Gmail API. The example shows `gmail.users.labels.list`, but like @barca mentioned, you could substitute that for `gmail.users.messages.send` as you try the quick start.

Cheers!

-----
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client
