### ISSUE TITLE
Does  access token Expires

### ISSUE THREAD

**Issue by Chethandsagar** [google/google-api-nodejs-client#517]
I'm using the API (v1) in the following way:

```js
var oauth2Client = new OAuth2(getGoogleCredentials().clientId, getGoogleCredentials().secret);
```
```js
oauth2Client = new OAuth2(this.clientId, this.clientSecret);
```
```js
this.oauth2Client.setCredentials({
  access_token: this.access_token,
  refresh_token: this.refresh_token,
  expiry_date: true
});
```

never got the 401 or 403  response .
currently i see the behavior that access token may be automatically refreshes. 
1) Does  gmail Api automatically refreshes the access token?
2) How do i hit with 401 & 403 response and how the gmail api refreshes it?

**Comment by jmdobry** [comment]
> 1) Does gmail Api automatically refreshes the access token?

Yes, that should be the case. From `README.md`:

>  OAuth2 client that allows you to retrieve an access token and refreshes the token and retry the request seamlessly if token is expired.

> 2) How do i hit with 401 & 403 response and how the gmail api refreshes it?

If the OAuth2 client discovers that the access token is expired, then it should automatically refresh the token. You won't see the 401 or 403 for an expired token.

@ryanseys Can confirm.

**Comment by jmdobry** [comment]
Closing as this does not appear to be an issue. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information such as:

* Expected behavior
* Actual behavior
* Code samples
* Version numbers
* References docs or other links

Or, consider opening a Pull Request.

__Otherwise, support questions are handled on [Stack Overflow][stackoverflow].__ [![Ask a question on Stackoverflow][overflowimg]][stackoverflow]

[overflowimg]: https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/stackoveflow-tag.png
[stackoverflow]: http://stackoverflow.com/questions/tagged/google-api-nodejs-client

**Comment by ZitRos** [comment]
> If the OAuth2 client discovers that the access token is expired, then it should automatically refresh the token. You won't see the 401 or 403 for an expired token.

Having `oauth2Client`,

Does anyone know the way to check if the token was refreshed and get a new one? I have never found this in the docs. This stands for a common reason — I want to keep always up-to-date token in my database.

Thanks!

Notifying @jmdobry @Chethandsagar

**Comment by Alex-Mann** [comment]
I also face the same issue. I was originally going call `oauth2Client.refreshAccessToken()` manually and save the updated token, but it seems that this method is deprecated.

Is the method that @ZitRos posted the elegant solution or has someone discovered a better way?
