### ISSUE TITLE
Refresh token did not work properly

### ISSUE THREAD

**Issue by abhaygarg** [google/google-api-nodejs-client#583]
Hi , I am using google api nodejs , I try to get data from google Anaytics 

``` js
var google = require('googleapis');
var OAuth2Client = google.auth.OAuth2;
var CLIENT_ID = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
var CLIENT_SECRET = 'xxxxxxxxxxxxxxxxxxxxxx';
//var REDIRECT_URL = 'http://yieldops.co/oauth2Callback';
var REDIRECT_URL = 'http://localhost:8000/oauth2Callback';
var oauth2Client = new OAuth2Client(CLIENT_ID, CLIENT_SECRET,REDIRECT_URL);

var credentials={}
credentials.expiry_date= "1463514280558",
credentials['refresh_token']="aaaaaaaaa"
credentials['access_token']="aaaaaaaaaaaaaaa"
oauth2Client.setCredentials(credentials)

var gauth = {
    'auth': outh2Client,
    'ids': 'ga:101' ,
    'start-date': '2016-01-01',
    'end-date': 'today',
    'metrics': 'ga:impressions,ga:sessions,ga:pageviews',
    'dimensions': 'ga:date'
}

analytics.data.ga.get(gauth, function (err, gaData) {
    console.log("err 1234",err)
    console.log("gaData ",gaData)
    //console.log("ga",Object.keys(gaData))
})
```

Now the problem is if access token is not expire then it give me data , and if access token is expire then it gave me 400 error Invalid grant . And if I remove expiry_date from credentials then it gave me error 
{ [Error: Invalid Credentials]
  code: 401,
  errors: 
   [ { domain: 'global',
       reason: 'authError',
       message: 'Invalid Credentials',
       locationType: 'header',
       location: 'Authorization' } ] }

**Comment by ddimitrioglo** [comment]
Confirm! I have the same issue...

**Comment by courthead** [comment]
@abhaygarg I'm not sure if this is your issue, but shouldn't `expiry_date` be set to an integer, not a string?

**Comment by JustinBeckwith** [comment]
Greetings folks!  A few things here:

1. You should never really set the expiry_date yourself.  We populate that when we acquire an access_token from the server. 

2. If you are setting a refresh_token - you need to make sure that the service you're trying to use requires the same scopes as those used to request the initial refresh_token.  Otherwise, you will end up with `invalid_grant` :) 

We've made a lot of changes here recently.  If you're still running into problems - please do let me know!
