### ISSUE TITLE
Use Admin API without admin user

### ISSUE THREAD

**Issue by simon-tannai** [google/google-api-nodejs-client#615]
Hello,

I'm using google-api-nodejs-client v12.2.0 for a studies project to create a small ERP.
In this project, I create an oAuth 2.0 authentification. This authentification work fine with the admin user, but when a standard user try to login, an error is thrown:

`Error: Not Authorized to access this resource/api`

This error is returned by my get user method:

`const ADMIN_API = googleapis.admin('directory_v1');`

```
return new Promise((resolve, reject) => {

  if( typeof userKey !== 'string' && typeof userKey !== 'number' ) {
    reject('User key must be a string or a number !');
    return false;
  }

  ADMIN_API.users.get({
    auth: auth,
    userKey: userKey,
    projection: 'full',
  },
  (err, response) => {
    if (err) {
      console.log('ADMIN_API returned an error: ' + err);
      reject(err);
      return false;
    }
    else {
      console.log(response);
      resolve(response);
    }
  });
});`
```

I need this method to check if the user is an admin or not and get some informations.

My first question is: It's the best solution to return user's informations ?

If yes, I think I must use a delegate user (as explained here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount), but I have not find any documentation about how to use a delegate user with google-api-nodejs-client.

Any idea ?

**Comment by jmdobry** [comment]
I'm sorry, but I'm unfamiliar with the Admin API. You say it succeeded when a known admin user made the request, so perhaps the request is failing because a user must be an admin to make that particular request? I haven't found a definitive answer on that point though.

Have you tried using a service account? Basically:

1. Create a service account
1. Download the json key file 
1. Set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the path to where you downloaded the key file
1. Set the `GCLOUD_PROJECT` environment to your project ID
1. Use [Application Default Credentials](https://github.com/google/google-api-nodejs-client#choosing-the-correct-credential-type-automatically) to get an auth client (replace the scopes in the example with the scopes you need from [here](https://developers.google.com/admin-sdk/directory/v1/guides/authorizing#OAuth2Authorizing))

Something like this:

```js
var google = require('googleapis');
var admin = google.admin('directory_v1');

function getUser (userKey, callback) {
  google.auth.getApplicationDefault(function (err, authClient) {
    if (err) {
      return callback(err);
    }

    if (authClient.createScopedRequired && authClient.createScopedRequired()) {
      authClient = authClient.createScoped([
        'https://www.googleapis.com/auth/admin.directory.user'
      ]);
    }
    
    admin.users.get({
      auth: authClient,
      userKey: userKey,
      projection: 'full'
    }, callback);
  });
}
```

**Comment by wellczech** [comment]
Use service account, which impersonates known admin to call Directory API; or change Directory API request to contain viewType = "domain_public" (that can be called by non-admin user)
https://developers.google.com/admin-sdk/directory/v1/reference/users/list
https://developers.google.com/admin-sdk/directory/v1/guides/manage-users#retrieve_users_non_admin

**Comment by 3thanZ** [comment]
Hi @jmdobry 

I tried the method that you have provided above but still encounter the same error as @simon-tannai. Do I need to impersonate an admin user to be able to make Admin SDK calls?

**Comment by wellczech** [comment]
The client needs to act on behalf of admin account when modifying Directory. Try one of below options.

a) Use service account with certificate. Register client in gsuite console for domain wide delegation of authority. During API calls impersonate known admin.

b) let admin authenticate tool. Initiate auth flow for installed apps and request offline access. Store refresh token. Use stored token in authentication client to get access tokens.

**Comment by 3thanZ** [comment]
Thanks @wellczech for the information. Your option (a) is exactly what I am trying to achieve, but could not find a way to specify the admin user to impersonate using @jmdobry 's sample code. Do you know how I can specify the admin user's email address to impersonate? I have already delegated domain wide access to the service account in Google Admin.

**Comment by wellczech** [comment]
@3thanZ check example https://github.com/google/google-api-nodejs-client/blob/master/samples/jwt.js

google.auth.JWT(client_email, path_to_pem_file, private_key, scopes, impersonated_email)

You can get client_email and private key from Cloud Console. Use either path_to_file or private_key, leave other null.
Last argument is used for impersonation. If null, your app acts on behalf the service account, if account email address is used, that account is impersonated. Don't forget to add your app to approved apps in GSuite admin console (Security -> advanced -> manage 3rd party access), otherwise impersonation won't work.

**Comment by 3thanZ** [comment]
Thanks @wellczech 

Not possible using this method? Was hoping to use the automatic auth method so that we can use the default credentials once the application is uploaded to Google Cloud Functions
```
google.auth.getApplicationDefault(function (err, authClient) {
...
});
```

**Comment by wellczech** [comment]
@3thanZ I once wanted to solve the same thing (AppEngine+Java), but gave up. I use default credential for communication between app modules/services and different credential for user authentication.

I'm really curious if it is possible or not.

**Comment by 3thanZ** [comment]
I tried digging around the source code but could not find any method of
setting the subject (user to impersonate) for this. I'll log an issue for
this.

Best regards,
Ethan Siew
Mobile: +6012 3822 032

**Comment by 3thanZ** [comment]
@wellczech I read the code at https://github.com/google/google-api-nodejs-client and found the solution. Basically getApplicationDefault has an override like that you can use to pass in the subject to impersonate:

```
google.auth.getApplicationDefault({
    subject: 'person@to.impersonate'
}, function (err, authClient, projectId) {
    ...
});
```

Hope you find this interesting.

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like this issue has been resolved.  If you're still running into issues - let us know!
