### ISSUE TITLE
request.pipe can leak credentials if it needs to refresh tokens

### ISSUE THREAD

**Issue by jmdobry** [google/google-api-nodejs-client#625]

**Comment by Aspie96** [comment]
Thank you very much for opening this issue.

I hope someone can solve it (although it looks hard to me).

**Comment by SamuelePilleri** [comment]
Ok, so I dived into the code and brought out something interesting.

As we know, all APIs refer to [createAPIRequest](https://github.com/google/google-api-nodejs-client/blob/master/lib/apirequest.js#L57) which itself, at line [apirequest.js:179](https://github.com/google/google-api-nodejs-client/blob/master/lib/apirequest.js#L179) uses an `authClient` to handle the authentication and request.
This `authClient` is of type `OAuth2Client` whose `request` method is defined here: [oauth2client.js:338](https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/oauth2client.js#L338).

And here we get to the core of the problem.

We can easily see that only the first request is returned ([oauth2client.js:377](https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/oauth2client.js#L377)) even when the token has to be refreshed (see [oauth2client.js:357](https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/oauth2client.js#L357)). We can understand that because the lines are almost identical.

So it is obvious that, if we want to be able to pipe requests, we have to return the correct one. But how? Promises? It should also be taken care not to consume the file unless it's a token, otherwise we won't be able to pipe it any more.

Ideas?

**Comment by JustinBeckwith** [comment]
This is fixed now that we've moved to axios.  The `.pipe` happens inside of the callback with `res.data`.  The callback is invoked *after* the token refresh is complete.
