### ISSUE TITLE
Google Drive Api v3 Create Shared File

### ISSUE THREAD

**Issue by aalireza439** [google/google-api-nodejs-client#640]
I am using Node.js google-api client for creating file in google drive normally when i create file everything work fine , here is an example :

```javascript

drive.files.create({
      resource: {
        name: 'Another File 5',
        mimeType: 'text/plain',
      },
      media: {
        mimeType: 'text/plain',
        body: 'It\'s Another Fucking File',
      }

    }, function(err,result){
        if(err) console.log(err) 
        else console.log(result)
    });
````

Now i want create a shared  `"shared": true` its give me this error :

```javascript

drive.files.create({
  resource: {
    name: 'Another File 5',
    mimeType: 'text/plain',
    "shared": true
  },
  media: {
    mimeType: 'text/plain',
    body: 'It\'s Another Fucking File',
  }

}, function(err,result){
    if(err) console.log(err) 
    else console.log(result)
});
````

Error :

```javascript
{ [Error: The resource body includes fields which are not directly writable.]
  code: 403,
  errors: 
   [ { domain: 'global',
       reason: 'fieldNotWritable',
       message: 'The resource body includes fields which are not directly writable.' } ] }
````
I tried this in Google APIs Explorer and gave same error.

I am new to google Api and appreciate any help.

**Comment by jmdobry** [comment]
I assume you're using the v3 Drive API. Looking at the documentation (https://developers.google.com/drive/v3/reference/files/create#request-body), it doesn't look like `shared` is a valid field for request body. It looks like you want the `viewersCanCopyContent` or `writersCanShare` fields.

**Comment by wangbourne** [comment]
so how to create a shareable link?

**Comment by jmdobry** [comment]
You may be able to share the `webViewLink` property of the [Files resource](https://developers.google.com/drive/v3/reference/files#resource). Sharing that link doesn't change permissions on the file though. You'd have to do that: https://developers.google.com/drive/v3/reference/permissions

**Comment by wangbourne** [comment]
@jmdobry , you are right, thanks :)

**Comment by 0x42h** [comment]
I just created a folder. From that, I receive the File resource object, but the webViewLink property is empty. What am I doing wrong?

What I expect is that new files or folder would automatigcally have the webViewLink.

I also seem to be unable to find the right documentation for setting the right permissions on that webViewLink, in this case the publicly shared && not indexed (secret link or whatever you'd like to call it). 

Any pointers?

**Comment by missou74** [comment]
@0x42h, I'm not  using the nodejs client but i had the same issues with java client.
The client is based on the REST API where the problem lies as Shoster says the 6 February on https://github.com/google/google-api-php-client/issues/1257
For getting the webViewLink make another file request with your fileId and specify webViewLink field as query parameter, then the webViewLink will be available.
This will only give you the webViewLink, if you need to share with anyone who has this link, you need to make a permission request using the following persmission value: 
role:"reader"
type:"anyone"

I supposed using node client, the code should look like something like that for getting the link:

```js
drive.files.get({
      fileId: 'yourFileId'
      fields: 'webLinkView'
      }, function(err,result){
        if(err) console.log(err) 
        else console.log(result)
    });
```
Then for make the file shared for anyone
```js
drive.permissions.create({
      fileId: 'yourFileId'
      permission:{
          role:"reader"
          type:"anyone"
      }}, function(err,result){
        if(err) console.log(err) 
        else console.log(result)
    });
```
Could check that and post the exact syntax ?

**Comment by rainabba** [comment]
Great example at: https://developers.google.com/drive/api/v3/manage-sharing

I was looking for the same behavior; defining sharing during file.create, but so far I don't see that supported and it must be done in 2 transactions as @missou74 said.

**Comment by rainabba** [comment]
Btw, the following library WILL be getting renamed and released to NPM soon[ish] so you may not want to use it directly YET (though I do in production), but  between lib/index.js and test/index.js, you'll find lots of useful code (or use the library, but watch for the update and install for now with git+https://github.com/rainabba/oauth-token-generator-google.git )

Do not use my auth library yet though (also unreleased) because it doesn't renew tokens yet (which is fine for development, but not production), but mine only provides an auth object as many others and you likely already have that setup anyway.

**Comment by 0x42h** [comment]
@missou74 Thanks for the tip. I was using the PHP lib, however. I just ended up here, as I found it to be the same issue, in spite of different client libraries. Due to time pressure I ended up constructing the link myself, based on example I had, because apparently the permissions that I applied were function correctly.

**Comment by maikokuppe** [comment]
> Then for make the file shared for anyone
> 
> ```js
> drive.permissions.create({
>       fileId: 'yourFileId'
>       permission:{
>           role:"reader"
>           type:"anyone"
>       }}, function(err,result){
>         if(err) console.log(err) 
>         else console.log(result)
>     });
> ```
> 
> Could check that and post the exact syntax ?

The key `permission` must be replaced by `resource`, as you can see [here](https://developers.google.com/drive/api/v3/manage-sharing#examples) (choose Node.js as the code language)

 ```js
 drive.permissions.create({
       fileId: 'yourFileId'
       resource:{
           role:"reader"
           type:"anyone"
       }}, function(err,result){
         if(err) console.log(err) 
         else console.log(result)
     });
 ```

**Comment by lucasmoglia** [comment]
Hi!

I'm using googleapis v3 and I've created a shared file following this steps:

1) Create a file
```
let file = await this.drive.files.create({
            requestBody: {
              name: 'Test'
            },
            media: {
              mimeType: _mimeType,
              body: _body
            }
        });
console.log(file);
```
2) Create permissions for that file (using the fileId from Step 1)
```
await this.drive.permissions.create({
          fileId: file.data.id,
          resource: {
            role:"reader",
            type: "anyone",
            allowFileDiscovery: true
          }
        });
```

3) Now if you get the file, you can use `webContentLink` or `webViewLink`!
```
let file = await this.drive.files.get({
          fileId: file.data.id,
          fields: '*' // to show every existing field
          });
console.log(file);
```
