### ISSUE TITLE
Error: User does not have an Adsense account

### ISSUE THREAD

**Issue by richzw** [google/google-api-nodejs-client#674]
Hi 

I got one error as below

```
An error occured { [Error: User does not have an AdSense account.]
  code: 403,
  errors:
   [ { domain: 'global',
       reason: 'noAdSenseAccount',
       message: 'User does not have an AdSense account.' } ] }
```

With the following codes

```javascript
google.auth.getApplicationDefault(function (err, authClient) {
	if (err) {
	        return console.log('Failed to get the default credentials: ' + String(err));
	}
	if (authClient.createScopedRequired && authClient.createScopedRequired()) {
		// Scopes can be specified either as an array or as a single, space-delimited string.
		authClient = authClient.createScoped(['https://www.googleapis.com/auth/adsense']);
	}
	var projectId = 'my-adsense-project-1362108';
	var adsense = google.adsense({version: 'v1.4', auth: authClient, project: projectId});

	var params = {
		accountId: 'pub-9014771234133935',
		startDate: '2016-11-10',
		endDate: '2016-11-11',
		dimension: ['AD_UNIT_ID', 'AD_UNIT_NAME'],
		metric: ['AD_REQUESTS', 'CLICKS']
	};
	adsense.accounts.reports.generate(params, function (err, report) {
		if (err) {
		  return console.log('An error occured', err);
		}
		console.dir(report);
	});  
});
```

However, I try to test the same account with this [sample codes](https://github.com/google/google-api-nodejs-client/blob/master/samples/oauth2.js), it can get the report correctly.

Could someone help me figure out what wrong with above codes?

Thanks!

**Comment by jmdobry** [comment]
The sample code you referenced takes you through an OAuth 2.0 flow, where the code requests authentication codes in order to act on _your_ behalf, as in _your_ Google account. 

`getApplicationDefault` only works with Service Account-like credentials which are tied to projects, not people. Your application default credentials do not have any Adsense accounts. Your Adsense account is "user data", owned by your Google Account, not owned by a developer project.
