### ISSUE TITLE
searchanalytics.query returns { responseAggregationType: 'byProperty' } when no data is available

### ISSUE THREAD

**Issue by castilloandres** [google/google-api-nodejs-client#677]
```javascript
let searchAnalytics = await new Promise((resolve, reject) => {
      this.client.searchanalytics.query({
        siteUrl: siteUrl,
        resource: {
          startDate: options.startDate,
          endDate: options.endDate,
          dimensions: options.dimensions,
          rowLimit: 50
        }
      },
      (error, result) => {
        if (error) {
          error.statusCode = Number(error.code) || 500;
          return reject(error);
        }
        return resolve(result.rows);
      });
});
```

![gsc-no-data](https://cloud.githubusercontent.com/assets/16306312/20434598/c5b49ade-ada8-11e6-9135-d7ea513f34ad.png)

**Comment by jmdobry** [comment]
Can you describe what the expected behavior should be vs the actual? Is there an issue with the code in `google-api-nodejs-client`?

**Comment by castilloandres** [comment]
Unexpected behaviour in the [searchanalytics.query POST request](https://github.com/google/google-api-nodejs-client/blob/548263fe8e64b9af27c9b21cc7a1179f8d0601dc/apis/webmasters/v3.js#L60) when there are no queries in the Google Search Console search analytics API.

Actual behaviour: the following object is returned
`{ responseAggregationType: 'byProperty' }`

Expected behaviour: return 404 or empty array. Something more descriptive of what is really happening that there are no queries in the GSC search analytics API.

**Comment by jmdobry** [comment]
`webmasters.searchanalytics.query` always returns a `SearchAnalyticsQueryResponse` object, which has a property called `responseAggregationType`. The lack of the `rows` property in the response can be considered the equivalent of `rows: []`. From the APIs perspective, the following two responses are the same:

```js
{
  responseAggregationType: 'byProperty'
}
```
```js
{
  responseAggregationType: 'byProperty',
  rows: []
}
```

The API's details are here: https://www.googleapis.com/discovery/v1/apis/webmasters/v3/rest

I have frequently seen this happen with Google APIs, when there are no results, instead of returning an empty array, they just omit the property from the response. If you think about it, over the years across all of Google's APIs that's probably saved _many_ bytes of empty arrays that didn't have to be sent over the wire.

**Comment by vipinstaplelogic** [comment]
"responseAggregationType": "byProperty"

**Comment by vipinstaplelogic** [comment]
I am also facing  this issue in GSC Query
