### ISSUE TITLE
getApplicationDefault seems incompatible with googlesheets.spreadsheets.values.append

### ISSUE THREAD

**Issue by nikkwong** [google/google-api-nodejs-client#686]
It seems like ```google.auth.getApplicationDefault``` does not support the ```googlesheets.spreadsheets.values.append``` method for the sheets v4 api. I have the scope 

                var scopes = ['https://www.googleapis.com/auth/spreadsheets'];
                authClient = authClient.createScoped(scopes);

set, and methods like ```googlesheets.spreadsheets.values.get``` work, but ```.append``` returns 
```The caller does not have permission```. 

Any help here?

**Comment by jmdobry** [comment]
I doubt `google.auth.getApplicationDefault` supports the Google Sheets API at all. Spreadsheets, as a resource, are owned by individual Google accounts, e.g. `your.name@gmail.com`. Therefore your code needs to use OAuth 2.0, requesting permission of a Google user in order to operate on spreadsheets on behalf of that user.

You could easily adapt one of these [Google Drive API samples](https://github.com/google/google-api-nodejs-client/tree/master/samples/drive) (which use OAuth 2.0) to do something with the Google Sheets API.

`google.auth.getApplicationDefault` is typically used for APIs used in server-to-server communication, where resources are owned by Google Developer projects (not individual users) and the authentication credentials come from a Service Account key file. A good example of this is the Google Compute Engine API.
