### ISSUE TITLE
googleapi.drive.files.watch returns Error: entityResource

### ISSUE THREAD

**Issue by monrus** [google/google-api-nodejs-client#796]
Hello, here is my code:

```js
export function watchFile(auth, fileId, callback) {
  const service = google.drive('v3')
  service.files.watch({ auth, fileId }, (err, response) => {
    if (err) {
      console.log(`Drive API returned ${err}`)
    }
    callback(response)
  })
}
```
and it's returned Error: entityResource
When i tried watch file on https://developers.google.com/drive/v3/reference/files/watch the error appears again

**Comment by christianguevara** [comment]
You are missing a requestBody object containing:

`{
  "kind": "api#channel",
  "id": string,
  "resourceId": string,
  "resourceUri": string,
  "token": string,
  "expiration": long,
  "type": string,
  "address": string,
  "payload": boolean,
  "params": {
    (key): string
  }
}`

As stated in the [docs](https://developers.google.com/drive/api/v3/reference/files/watch)

I don't think the `auth` object is needed since the library takes care of it.

`export function watchFile(auth, fileId, callback) {
  const service = google.drive('v3')
  service.files.watch({fileId, requestBody }, (err, response) => {
    if (err) {
      console.log(`Drive API returned ${err}`)
    }
    callback(response)
  })
}`
