### ISSUE TITLE
What is the correct way to use OAuth2?

### ISSUE THREAD

**Issue by megamindbrian** [google/google-api-nodejs-client#822]
There seems to be some ambiguity in using the Google APIs.  How do I check if an old token has access to a new scope?

My code looks like this example:
https://developers.google.com/drive/v3/web/quickstart/nodejs

But this example shows the client.init() function using scopes:
https://developers.google.com/api-client-library/javascript/samples/samples#authorizing-and-making-authorized-requests

Is there a way to validate the scope using the OAuth2 layer, or do I have to connect to the drive service (for the first example), get and error, and then return back to setting up a new OAuth2 connection?  Seems a little counter-intuitive to get an authentication error from the service layer, that should happen when I create an OAuth2 client with right the scopes, right?

**Comment by JoeCodeswell** [comment]
I have something like this issue as well. 

I ALSO ran the [nodejs quicktart.](https://developers.google.com/drive/v3/web/quickstart/nodejs) 

BTW the Node.js Quickstart code seems a bit convoluted to me. I.E. it is not easily separable into logical functional alternatives. COULD this be due to the (high?) usage of callbacks?

I have opened a [StackOverflow question/issue here.](https://stackoverflow.com/q/47114172/601770)  

Would you please answer the SO item either here or there?

Thanks in advance.
Love and peace,
Joe Dorocak aka JoeCodeswell

**Comment by JustinBeckwith** [comment]
This issue was moved to google/google-auth-library-nodejs#336
