### ISSUE TITLE
Feautre request: reduce 'googleapis' module size

### ISSUE THREAD

**Issue by gauntface** [google/google-api-nodejs-client#906]
On a recent project I was using the googleapis module to access the YouTube api. When attempting to reduce the size of my docker container, I realised nearly 30MB was being consumed by the 'googleapis' module.

 It would be a good idea to break this up into multiple packages, shared logic in a core package that other packages depend on and individual packages for specific API groups.

**Comment by crisward** [comment]
Can't agree more. Noticed the package contains all the typescript files, map files and compiled js files. Adding a `.npm_ignore` file to remove all the `*.ts` and `*.map` files should substantially reduce this.

**Comment by JustinBeckwith** [comment]
When we get here, this will likely be done by providing individual npm modules for each target API.  Shipping the `*.d.ts` and *.js.map* files is very much by design.  These ensure the module works with TypeScript and really don't add substantial overhead.  FWIW - we do limit what gets bundled into the end module:
https://github.com/google/google-api-nodejs-client/blob/master/package.json#L16

**Comment by crisward** [comment]
I've just removed all the ts and map files and it's not unsubstantial. The package size goes from 40mb to 21mb. Shame there is no way to have a js / ts version. It's still my biggest npm dependency by a long way.

Individual npm modules would also be good. 

Thanks for the update!

**Comment by JustinBeckwith** [comment]
Fair point :) Going to track this over in #806!
